version: 2.1

jobs:
  install:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  check:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - install
  publish:
    jobs:
      - install:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /^.*$/
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build