version: 2.1

commands:
  install:
    description: "Install all NPM package dependencies"
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache-
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

executors:
  node:
    docker:
      - image: node:14.11.0

jobs:
  test:
    executor: node
    environment:
      JEST_JUNIT_OUTPUT_DIR: reports/
    steps:
      - checkout
      - install
      - run:
          name: Test
          command: npm test -- --reporters=default --reporters=jest-junit
      - store_test_results:
          path: reports
  deploy:
    executor: node
    steps:
      - run:
          name: "Install Git LFS"
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt install git-lfs
      - checkout
      - install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Compress Artifacts
          command: tar -cvzf build.tar.gz build
      - store_artifacts:
          path: build.tar.gz
      - add_ssh_keys:
          fingerprints:
            - "4d:47:b8:ab:8f:05:69:b4:82:f7:6b:b5:30:dc:5e:f3"
      - run:
          name: Deploy
          command: |
            git config user.email "support@circleci.com"
            git config user.name "CircleCI"
            npm run deploy

workflows:
  version: 2
  check:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
  publish:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/