version: 2.1

jobs:
  test:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: node:14.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: build
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  check:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
  publish:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /^.*$/