name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        uses: actions/setup-node@v1
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.sha }}
          path: build/
